### ISSUE TITLE
check for a valid IG and SFN on startup, rather than on mirror

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/poseidon#660]

**Comment by rashley-iqt** [comment]
I'm going to implement this as a straightforward log message for the moment.  However, it ocurrs to me that we may have misinterpreted @d-grossman 's original request.  Ultimately, we are checking to see if there is a span-fabric/interface group combo as a precursor to sending a PUT to the API in order to add a set of filters.  It might make more sense to, assuming that a span-fabric with the specified interface group doesn't exist, pop up a level and check if that the configured interface group exists and if it does issue a POST request to create a spanfabric with the configured name/interface group.
